server:
  port: 3231
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/user_p?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    username: root
    password: 20031028
    driver-class-name: com.mysql.cj.jdbc.Driver
